{% set name = "aospy" %}
{% set version = "0.1.2" %}
{% set sha256 = "253fd858a4771a7af487913d8d0082e0eb56ff38795db73ea4f414bf9e780ada" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.7
    - scipy >=0.16
    - pandas >=0.15.0
    - netcdf4 >=1.2
    - toolz >=0.7.2
    - dask >=0.12
    - xarray >=0.9.1
    - cloudpickle >=0.2.1

test:
  imports:
    - aospy
    - aospy.examples
    - aospy.test
    - aospy.test.data
    - aospy.test.data.objects
    - aospy.utils

  requires:
    - pytest >=2.7.1
    - pytest-catchlog >=1.0

about:
  home: http://github.com/spencerahill/aospy
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Automated gridded climate data analysis and management'

  description: |
     A framework that enables automated calculations using gridded
     climate data. Following some basic description of where your data
     lives and defining any functions of variables stored in that data
     you want to compute, aospy enables you to fire off an arbitrary
     number of calculations using that data.
  doc_url: http://aospy.readthedocs.io/
  dev_url: https://github.com/spencerahill/aospy

extra:
  recipe-maintainers:
    - spencerahill
