travis:
  secure:
    BINSTAR_TOKEN: TXgDWHnVR9KglKnPIB815lrr3kczU+6FY7dV9rpGUCqyBnzrJSYFfWTiWNMD75qD7uOeOhkgo1Xjtj19hxYfbxJ8sIgrZ6cpYRfJ/qDRZ7pllHt4rRLhk0ujg5X0FjPMtXBUcDKZ9t65dAWCDltvZ6gy1iwdgO/mt/233k6/OBPDy7zPnQAqfdg+jLTVaCV2cMMBTtb6ZanzdE6Hzc0JBVYpKI3CjftjeJljy97107x8R7cV4srCY7BcIpZulS2juF8S550FsOOzRoUcCk3wPBbUd3qfLfShKb65+/jueYv0pYJ274t/LOLaSxHF/rLvJ8loncEBjf4grOj0dUAqrEQF7tcMJlBdhdhkpg6KADauwjlUkm5cMp6mLoVYGU7Jt6OCq6CZQuv170AvycXF60y0SeQpe2dNuZYTM4/S/3HENBDttnoTrjTTJJXVBxagxb5PUgoQOrk2LN5PTZEYroEuW78ZAKyAbI9E4OSCblQjpLBxHhPIhv32NOBChV5qW4zrih7V3lVcCtTAaVs104fUWCP+q8ZpHF89CSVyT+kegwYqQslWqHk2cwk4mTqsKbgAiYKe/RoRCsrRy2dfNzi9mCAL4mNwUKcx2KtzfJDQsEv618DWz77MuufVY32j69p08MEh00OdMLBRSkGgopbe1pso/d8+0sKabwxbKYc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
